Q1. What is data encoding? How is it useful in data science?

In [ ]:
Answer = """  
Data encoding is the process of converting data from one form to another. In machine learning,
data encoding is used to convert categorical data into numerical data so that it can be used in machine learning models.
There are two popular techniques for encoding categorical data: Ordinal Encoding and One-Hot Encoding.
1. Ordinal Encoding:-

In ordinal encoding, each unique category value is assigned an integer value.
For example, “red” is 1, “green” is 2, and “blue” is 3.

This is called an ordinal encoding or an integer encoding and is easily reversible.
Often, integer values starting at zero are used.

For some variables, an ordinal encoding may be enough.
The integer values have a natural ordered relationship between each other and machine learning algorithms may be able to understand and harness,
this relationship.

It is a natural encoding for ordinal variables.
For categorical variables, it imposes an ordinal relationship where no such relationship may exist.
This can cause problems and a one-hot encoding may be used instead.

2. One Hot Encoding:-
For categorical variables where no ordinal relationship exists, the integer encoding may not be enough,
at best, or misleading to the model at worst.

Forcing an ordinal relationship via an ordinal encoding and allowing the model to assume a natural ordering between categories,
may result in poor performance or unexpected results (predictions halfway between categories).

In this case, a one-hot encoding can be applied to the ordinal representation.
This is where the integer encoded variable is removed and one new binary variable is added for each unique integer value in the variable.

How is it useful in data science:-
Data encoding is useful in data science because it helps to convert categorical data into numerical data,
which can be used in machine learning models. This helps to improve the accuracy of the models and make them more efficient.
"""

Q2. What is nominal encoding? Provide an example of how you would use it in a real-world scenario.

In [ ]:
Answer = """
Nominal encoding is a type of data encoding that is used to convert categorical data into numerical data.
Nominal data is data that does not have an inherent order, such as colors, names, or categories

An example of how nominal encoding can be used in a real-world scenario is in the analysis of customer data.
Suppose a company has a customer database that includes information such as the customer’s name, age, gender, and location.
The location data is nominal data because it does not have an inherent order.
To use this data in a machine learning model, the location data needs to be converted into numerical data using nominal encoding.
One way to do this is to use one-hot encoding, which creates a new binary feature for each category in the nominal data.
For example, if the location data includes categories such as “New York,” “Los Angeles,” and “Chicago,” then,
one-hot encoding would create three new binary features, one for each category.
Nominal encoding is useful in data science because it helps to convert categorical data into numerical data,
which can be used in machine learning models.
"""

Q3. In what situations is ORDINAL encoding preferred over one-hot encoding? Provide a practical example.

In [11]:
Answer = """
Ordinal encoding is preferred over one-hot encoding when the categorical variable has a natural order or ranking.
For example, in the context of machine learning, ordinal encoding can be used to encode the education level of a person,
where the education level has a natural order such as “high school”, “bachelor’s degree”, “master’s degree”, and "doctorate degree".

One-hot encoding is preferred when the categorical variable has no natural order or ranking. For example, in the context of machine learning,
one-hot encoding can be used to encode the color of a car, where the colors have no natural order or ranking

It is important to note that forcing an ordinal relationship via an ordinal encoding and allowing the model to assume a natural ordering,
between categories may result in poor performance or unexpected results (predictions halfway between categories).

Practical Example:-
Example for one hot encoding goes below.
"""
# !pip install sklearn
# from sklearn.preprocessing import LableEncoder
# from sklearn.preprocessing import OneHotEncoder

cat_data = ["apple" , "mango" , "apple" , "berry" , "mango" , "apple" , "berry" , "apple"];
# label = LabelEncoder();
# int_data = label.fit_transform(cat_data);
# int_data
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
label = preprocessing.LabelEncoder()

int_data = label.fit_transform(cat_data);
int_data = int_data.reshape(len(int_data) , 1);
onehot_data = OneHotEncoder(sparse = False);
onehot_data = onehot_data.fit_transform(int_data);
print("Categorical Data Encoded into integer values ...\n");
print(onehot_data);

Categorical Data Encoded into integer values ...

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [16]:
Ordinal_Encoding_Practical_Example = """ 
Python code for it goes below.
"""
from numpy import asarray;
from sklearn.preprocessing import OrdinalEncoder
data_set = asarray([['red'] , ['green'] , ['blue']]);
print(data_set)
encoder = OrdinalEncoder();
result = encoder.fit_transform(data_set);
print("\n*************** After ordinal Encoding ********\n");
print(result)

[['red']
 ['green']
 ['blue']]

*************** After ordinal Encoding ********

[[2.]
 [1.]
 [0.]]


Q4. Suppose you have a dataset containing categorical data with 5 unique values. Which encoding
technique would you use to transform this data into a format suitable for machine learning algorithms?
Explain why you made this choice.

In [ ]:
Answer = """
1. If I have a dataset containing categorical data with 5 unique values,
I can use either ordinal encoding or one-hot encoding to transform this data into a format suitable for machine learning algorithms.

2. If the categorical variable has a natural order or ranking, then ordinal encoding can be used.
If the categorical variable has no natural order or ranking, then one-hot encoding can be used.

3. In general, one-hot encoding is preferred over ordinal encoding because it does not assume any ordinal relationship,
between the categories and can be used for categorical variables with any number of unique values.
However, one-hot encoding can lead to the curse of dimensionality if the number of unique values is very large.

4. Ordinal encoding is preferred when the number of unique values is large and one-hot encoding would lead to the curse of dimensionality.
"""

Q5. In a machine learning project, you have a dataset with 1000 rows and 5 columns. Two of the columns
are categorical, and the remaining three columns are numerical. If you were to use nominal encoding to
transform the categorical data, how many new columns would be created? Show your calculations.

In [ ]:
Answer = """
1. If I want to use nominal encoding to transform the categorical data, I would create a new column for each unique value in the categorical columns.
2. Let’s assume that the first categorical column has 12 unique values and the second categorical column has 5 unique values.
Then, nominal encoding/one-hot encoding would create 12 + 5 = 17 new columns.
3. In general, if the first categorical column has n unique values and the second categorical column has m unique values,
then nominal encoding would create n + m new columns.
"""

Q6. You are working with a dataset containing information about different types of animals, including their
species, habitat, and diet. Which encoding technique would you use to transform the categorical data into
a format suitable for machine learning algorithms? Justify your answer.

In [ ]:
Answer = """ 
1. It is observed that variables species , habitat and diet are NOMINAL features with no natural order or ranking.
2. If the categorical variable has no natural order or ranking, then one-hot encoding can be used.
3. Hence One-Hot Encoding would be preffered in above case.
"""

Q7.You are working on a project that involves predicting customer churn for a telecommunications
company. You have a dataset with 5 features, including the customer's gender, age, contract type,
monthly charges, and tenure. Which encoding technique(s) would you use to transform the categorical
data into numerical data? Provide a step-by-step explanation of how you would implement the encoding.

In [30]:
Answer = """
To transform the categorical data in the customer churn dataset into numerical data, you can use either ordinal encoding or one-hot encoding.
If the categorical variable has a natural order or ranking, then ordinal encoding can be used.
For example, if the dataset contains information about the contract type of the customers, such as “month-to-month”, “one year”, and “two year”,
then ordinal encoding can be used to encode this information.
If the categorical variable has no natural order or ranking, then one-hot encoding can be used.
For example, if the dataset contains information about the gender of the customers, such as “male” and “female”,
then one-hot encoding can be used to encode this information.
Here are the steps to implement this encoding:
Identify the categorical variables in the dataset. In this case, the categorical variables are the customer’s gender and contract type.

Seperate Nominal and Ordinal Variables. In this case Gender is an Nominal variable, while contract type is ordinal variable.

Apply One Hot Encoding to Nominal Variable in this case Gender Variable.

Apply Ordinal Encoding to Ordinal Variable in this case contract type variable.

Scale Numerical data using StandardScaler

Combine all 3 encoding into single dataframe

Data is now ready for machine learning model
"""
import numpy as np
import pandas as pd

# Setting random seed 
np.random.seed(543)
n = 1000 # dataset size
gender = np.random.choice(['Male','Female'],size=n)
age = np.random.randint(low=25, high=65, size=n)
contract = np.random.choice(['monthly','quarterly','half yearly','yearly'], size=n)
monthly_charges = np.random.normal(loc=1000, scale=100,size=n)
tenure = np.random.randint(low=12, high=36, size=n)
churn = np.random.choice([1,0], p=[0.2,0.8], size=n)

# Creating dictionary
dct = {
    'gender':gender,
    'age':age,
    'contract':contract,
    'monthly_charges':monthly_charges,
    'tenure':tenure,
    'churn':churn
}

# Creating Dataframe
df = pd.DataFrame(dct);
df.head();

# Seperating X and Y.
X = df.drop(labels = ['churn'], axis = 1); # stores catogrical data.
Y = df[['churn']]; # stores nominal data.

# Performing one hot encoding on gender column.
from sklearn.preprocessing import OneHotEncoder
ohd = OneHotEncoder();
gender_ohd = ohd.fit_transform(X[['gender']]).toarray();
# gender_ohd
X_gender = pd.DataFrame(gender_ohd, columns = ohd.get_feature_names_out())
X_gender.head()

gender_Female  gender_Male
0            1.0          0.0
1            1.0          0.0
2            1.0          0.0
3            1.0          0.0
4            0.0          1.0

In [35]:
# Peforming Ordinal Encoding on Contract Type
from sklearn.preprocessing import OrdinalEncoder
# ord_enc = OrdinalEncoder(categories=[['monthly','quarterly','half yearly','yearly']])
# Getting ordinal dataframe
# contract_encoded = ord_enc.fit_transform(X[['contract']]).flatten()
# X_contract = pd.DataFrame(contract_encoded,columns=['contract'])
# X_contract.head()
ord_enc = OrdinalEncoder(categories=[['monthly' , 'quarterly', 'half yearly', 'yearly']]);
contract_encoded = ord_enc.fit_transform(X[['contract']]).flatten()
# print(contract_encoded)
X_contract = pd.DataFrame(contract_encoded, columns=['contract']);
X_contract.head()

contract
0       3.0
1       2.0
2       3.0
3       1.0
4       2.0

In [38]:
# Getting Numeric Variables.
X_numeric = X.select_dtypes(exclude='object');
X_numeric.head()

age  monthly_charges  tenure
0   34      1042.202157      25
1   36       966.337735      12
2   30      1165.040177      16
3   44      1002.266319      35
4   53      1043.851952      16

In [39]:
# Concatenating all three variables Nominal, Ordinal and Numerical.
X_encoded = pd.concat([X_numeric,X_contract,X_gender],axis=1)
X_encoded.head()

age  monthly_charges  tenure  contract  gender_Female  gender_Male
0   34      1042.202157      25       3.0            1.0          0.0
1   36       966.337735      12       2.0            1.0          0.0
2   30      1165.040177      16       3.0            1.0          0.0
3   44      1002.266319      35       1.0            1.0          0.0
4   53      1043.851952      16       2.0            0.0          1.0

In [40]:
# Applying standard scaler to entire encoded dataset.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_final = pd.DataFrame(scaler.fit_transform(X_encoded),columns=X_encoded.columns)
X_final.head()


age  monthly_charges    tenure  contract  gender_Female  gender_Male
0 -0.897852         0.446463  0.244225  1.354668       0.992032    -0.992032
1 -0.722935        -0.322028 -1.622281  0.462265       0.992032    -0.992032
2 -1.247688         1.690786 -1.047972  1.354668       0.992032    -0.992032
3 -0.023264         0.041921  1.679999 -0.430138       0.992032    -0.992032
4  0.763865         0.463175 -1.047972  0.462265      -1.008032     1.008032

In [42]:
# Train test split
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_final,Y,test_size=0.2, random_state=42, stratify=Y)

In [44]:
xtrain.head()

age  monthly_charges    tenure  contract  gender_Female  gender_Male
514 -0.635476        -0.898498 -1.478704  1.354668      -1.008032     1.008032
224 -1.072770        -0.721926 -1.191549 -1.322542      -1.008032     1.008032
845  1.463536        -0.933469 -0.617239  0.462265       0.992032    -0.992032
736  1.026242        -1.537408  0.962112 -1.322542       0.992032    -0.992032
792 -0.722935        -0.673444  0.818535 -0.430138       0.992032    -0.992032

In [45]:
ytrain.head()

churn
514      0
224      0
845      0
736      0
792      0

In [46]:
xtest.head()

age  monthly_charges    tenure  contract  gender_Female  gender_Male
855  0.676407         1.817057  0.244225 -0.430138       0.992032    -0.992032
942  0.064195        -0.282519 -1.335126  1.354668       0.992032    -0.992032
234 -0.897852         1.087411 -1.335126  0.462265       0.992032    -0.992032
108 -0.985311         1.015790 -1.622281  0.462265       0.992032    -0.992032
697  0.151654        -1.651405 -1.622281  1.354668       0.992032    -0.992032

In [47]:
ytest.head()

churn
855      0
942      0
234      0
108      0
697      0