In [15]:
# Consider below code to answer further questions?
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5'];
array_list = np.array(object = list_);

In [16]:
# Question 1 Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables?
ans = """Yes,
there is a difference in the data type of variables list_ and array_list. list_ is a Python list object,
while array_list is a NumPy array object."""
print("Datatype of list_ :- " , type(list_));
print("Datatype of array_list:- ", type(array_list));

Datatype of list_ :-  <class 'list'>
Datatype of array_list:-  <class 'numpy.ndarray'>


In [17]:
#Question 2 Write a code to print the data type of each and every element of both the variabels list_ and array_list.
for item in list_:
    print(f"DataType for element {item} present in list is {type(item)}");
for item in array_list:
    print(f"DataType for element {item} present in array_list is {type(item)}");

DataType for element 1 present in list is <class 'str'>
DataType for element 2 present in list is <class 'str'>
DataType for element 3 present in list is <class 'str'>
DataType for element 4 present in list is <class 'str'>
DataType for element 5 present in list is <class 'str'>
DataType for element 1 present in array_list is <class 'numpy.str_'>
DataType for element 2 present in array_list is <class 'numpy.str_'>
DataType for element 3 present in array_list is <class 'numpy.str_'>
DataType for element 4 present in array_list is <class 'numpy.str_'>
DataType for element 5 present in array_list is <class 'numpy.str_'>


In [20]:
#Question 3 considering the following changes in the variable, arrya_list
array_list = np.array(object = list_ , dtype = int);
# will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list?
ans = """ Yes there will be difference in the data type of the elements present in array_list,
but not in case of List_."""
for item in list_:
    print(f"DataType for element {item} present in list is {type(item)}");
for item in array_list:
    print(f"DataType for element {item} present in array_list is {type(item)}");

new_type = "<class 'numpy.int64'>";
old_type = "<class 'numpy.str_'>";
print("****************************************************");
print(f"Datatype changes from {old_type} to {new_type}");

DataType for element 1 present in list is <class 'str'>
DataType for element 2 present in list is <class 'str'>
DataType for element 3 present in list is <class 'str'>
DataType for element 4 present in list is <class 'str'>
DataType for element 5 present in list is <class 'str'>
DataType for element 1 present in array_list is <class 'numpy.int64'>
DataType for element 2 present in array_list is <class 'numpy.int64'>
DataType for element 3 present in array_list is <class 'numpy.int64'>
DataType for element 4 present in array_list is <class 'numpy.int64'>
DataType for element 5 present in array_list is <class 'numpy.int64'>
****************************************************
Datatype changes from <class 'numpy.str_'> to <class 'numpy.int64'>


In [21]:
# consider below code to answer further questions?
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [23]:
#Question 4 Write a code to find the following characteristics of variable, num_arrya?
# i) shape ii) size.
print("Characteristics of num_array shape:- " , num_array.shape);
print("Characteristics of num_array size:- " , num_array.size);

Characteristics of num_array shape:-  (2, 3)
Characteristics of num_array size:-  6


In [24]:
#Question 5 Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
zeros_matrix = np.zeros((3,3));
print(zeros_matrix);

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
#Question 6 Create an identity matrix of shape(5,5) using numpy functions?
identity_matrix = np.eye(5);
print(identity_matrix);

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
