Question 1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region.


In [1]:
import pandas as pd;
import numpy as np;
Region_A = [10, 15, 12, 8, 14]
Region_B = [18, 20, 16, 22, 25]
mean_a = np.mean(Region_A);
mean_b = np.mean(Region_B);
print("Mean for region A is " , mean_a);
print("Mean for region B is " , mean_b);

Mean for region A is  11.8
Mean for region B is  20.2


Question 2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.


In [4]:
import statistics as stats;
arr = [4,5,2,3,5,4,3,2,4,5]
mode_arr = np.array(arr);
print("Mode is " , stats.mode(mode_arr))

Mode is  4


Question 3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [5]:
department_a = [5000,6000,5500,7000];
department_b = [4500, 5500, 5800, 6000, 5200];
dept_a_median = stats.median(np.array(department_a))
dept_b_median = stats.median(np.array(department_b))
print("Department A " , dept_a_median)
print("Department B " , dept_b_median)

Department A  5750.0
Department B  5500


Question 4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [7]:
data = [25.5, 24.8, 26.1, 25.3, 24.9];
mx = max(data)
mn = min(data)
print("Range is " , "(", mx , " , " , mn , ")")

Range is  ( 26.1  ,  24.8 )



Question 5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [16]:
import numpy as np
import scipy.stats
import math
group_a = [85, 90, 92, 88, 91]
group_b = [82, 88, 90, 86, 87]
# I will be performing two sample test for independent population size.
# so first find mean of both the samples.
n1 = len(group_a)
n2 = len(group_b)
x_1 = np.mean(group_a)
x_2 = np.mean(group_b)
# print(mean_a)
# Now calculate combined standard deviation
sum_a = 0
for i in group_a:
    sum_a = sum_a + (i - x_1)*(i - x_1)
    
sum_b = 0;
for i in group_b:
    sum_b =sum_b + (i - x_2) * (i - x_2)

combined_sd = (sum_a + sum_b)/(n1 + n2 - 2)
combined_sd = math.sqrt(combined_sd)
standard_sd = combined_sd/(math.sqrt((1/n1) + (1/n2)))
t_cal = (x_1 - x_2)/standard_sd
degree_of_freedom = n1 + n2 - 2;

# print(t_cal)

print("Value of calculated t variable is " , t_cal);

t_table = scipy.stats.t.ppf(q=1-.05/2,df=degree_of_freedom)
# print(t_table)
print("value of tabular value of t is " , t_table);
print()
if t_cal > t_table:
    print("H0 rejected, which means that means of two samples are significantly different!")
else:
    print("H0 accepted, which means that means of two samples are not significantly different!")
    

Value of calculated t variable is  0.5725011578657094
value of tabular value of t is  2.3060041350333704

H0 accepted, which means that means of two samples are not significantly different!


Question 6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [21]:
advert = [10, 15, 12, 8, 14]
sales = [25, 30, 28, 20, 26]
x = np.mean(advert)
y = np.mean(sales)
sum = 0;
sum_a = 0;
sum_b = 0;
for i in range(0, len(advert)):
    # print(advert[i])
    sum = sum + (advert[i] - x)*(sales[i] - y)
    sum_a = sum_a + (advert[i] - x)*(advert[i] - x);
    sum_b = sum_b + (sales[i] - y)*(sales[i] - y);

denominator = math.sqrt(sum_a * sum_b);
numerator = sum;
r = numerator/denominator
print("Correlation Coefficient for the given samples is " , r)


Correlation Coefficient for the given samples is  0.8757511375750133


Question 7 Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights.


In [33]:
import statistics as stats
heights = [160, 170, 165, 155, 175, 180, 170]
sd = np.std(heights)
print(sd)


7.953949089757174


Question 8. Scenario :A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
emp = [2, 3, 5, 4, 6, 2, 4];
job = [7, 8, 6, 9, 5, 7, 6];

x = emp
y = job
X_train, X_test, y_train, y_test = train_test_split( x, y, train_size = 0.7, test_size = 0.3, random_state = 100 )
x_train_sm = sm.add_constant(X_train)
lr = sm.OLS(y_train, x_train_sm).fit()
# lr.params
print(lr.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.229
Model:                            OLS   Adj. R-squared:                 -0.157
Method:                 Least Squares   F-statistic:                    0.5926
Date:                Sat, 15 Jul 2023   Prob (F-statistic):              0.522
Time:                        12:08:06   Log-Likelihood:                -6.7223
No. Observations:                   4   AIC:                             17.44
Df Residuals:                       2   BIC:                             16.22
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          8.7500      2.756      3.175      0.0

/opt/conda/lib/python3.10/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [16]:
# Add a constant to X_test
X_test_sm = sm.add_constant(X_test)
y_pred = lr.predict(X_test_sm)
y_pred

array([7.25, 6.25, 7.75])

In [18]:
# Evaluation metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
#RMSE value
print( "RMSE: ",np.sqrt( mean_squared_error( y_test, y_pred ) ))
#R-squared value
print( "R-squared: ",r2_score( y_test, y_pred ) )

RMSE:  0.6291528696058952
R-squared:  0.4062500000000011


Question 9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
   Medication B: [15, 17, 16, 14, 18]
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


In [66]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import scipy.stats
a = [10, 12, 14, 11, 13]
b = [15, 17, 16, 14, 18]
x_a = np.mean(a)
x_b = np.mean(b)
n_a = len(a)
n_b = len(b)
T = x_a + x_b
N = n_a + n_b
Correction_factor = (T*T)/N
sum_a = 0
sum_b = 0
sum_squares_a = 0
sum_squares_b = 0
for i in range(0 , len(a)):
    sum_a = sum_a + a[i]
    sum_b = sum_b + b[i]
    sum_squares_a = sum_squares_a + a[i]*a[i]
    sum_squares_b = sum_squares_b + b[i]*b[i]
sum_a = sum_a * sum_a
sum_b = sum_b * sum_b
ssc = (sum_a/n_a) + (sum_b / n_b) - Correction_factor
sst = sum_squares_a + sum_squares_b - Correction_factor
sse = sst - ssc
msc = ssc
mse = sse/(N - 2)
df = N-1
F = 0
dfn = 0
dfd = 0
if mse > msc:
    F = mse / msc
    dfn = N - 2
    dfd = 1
else:
    F = msc/msc
    dfn = 1
    dfd = N - 2

F_c = scipy.stats.f.ppf(q=1-.05, dfn=dfn, dfd=dfd)

print("Value of F calculated :", F)
print("Value of F critical at 0.05 signficance level:", F_c)
if F > F_c:
    print("There is significant difference in mean!!")
else:
    print("There is no significant difference in mean!!");

Value of F calculated : 1.0
Value of F critical at 0.05 signficance level: 5.317655071578714
There is no significant difference in mean!!


Question 10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings.


In [20]:
data = [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
ans = np.percentile(data, 75)
ans

8.75

Question 11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [68]:
Null_hypothesis = "Mean weight does not differ significantly!!"
Alternate = "Mean weight differs signicantly!!"
import numpy as np
from scipy import stats 
from numpy.random import seed
from numpy.random import randn
from numpy.random import normal
from scipy.stats import ttest_1samp
data = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
alpha = 0.05
t_stat, p_value = ttest_1samp(data, popmean=10)
print("T-statistic value: ", t_stat)  
print("P-Value: ", p_value)
if(p_value <= alpha):
    print(Alternate);
else:
    print(Null_hypothesis)

T-statistic value:  1.5126584522688367
P-Value:  0.19077595151110102
Mean weight does not differ significantly!!


Question 12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [75]:
Null = "There is no significant difference!!"
Alternate = "There is significant difference!!"
alpha = 0.05
A = [100, 120, 110, 90, 95]
B = [80, 85, 90, 95, 100]
import numpy as np
from scipy import stats 
from numpy.random import seed
from numpy.random import randn
from numpy.random import normal
from scipy.stats import ttest_1samp
data = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
alpha = 0.05
t_stat, p_value = ttest_1samp(data, popmean=10)
print("T-statistic value: ", t_stat)  
print("P-Value: ", p_value)
if(p_value <= alpha):
    print(Alternate);
else:
    print(Null)

T-statistic value:  1.5126584522688367
P-Value:  0.19077595151110102
There is no significant difference!!


Question 13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [70]:
import scipy.stats as st
data =  [7, 9, 6, 8, 10, 7, 8, 9, 7, 8] ;
x = np.mean(data)
rnge = st.t.interval(alpha=0.95, df=len(data)-1, loc=x, scale=st.sem(data))
print(rnge)

(7.043561120599888, 8.756438879400113)


/tmp/ipykernel_77/1496723857.py:4: DeprecationWarning: Use of keyword argument `alpha` for method `interval` is deprecated. Use first positional argument or keyword argument `confidence` instead.
  rnge = st.t.interval(alpha=0.95, df=len(data)-1, loc=x, scale=st.sem(data))


Question 14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperature.


In [60]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
x =   [20, 22, 23, 19, 21];
y =  [8, 7, 9, 6, 8]
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)
# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)

linreg = LinearRegression()
x_train = np.array(x_train).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)
linreg.fit(x_train, y_train)

y_pred = linreg.predict(np.array(x_test).reshape(-1,1))
print("Predicted Array: ")
y_pred

Predicted Array: 


array([[8.]])

Question 15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
    Group A: [4, 3, 5, 2, 4]
  Group B: [3, 2, 4, 3, 3]
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


In [76]:
x_1 = [4, 3, 5, 2, 4]
x_2 =  [3, 2, 4, 3, 3]
statistic , p_value = stats.mannwhitneyu(x_1, x_2, alternative='two-sided')
Null = "There is no difference!!"
Alternate ="There is significant difference!!"
alpha = 0.05
if(p_value < 0.05):
    print(Null)
else:
    print(Alternate)

There is significant difference!!


Question 16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [59]:
import numpy as np

#define array of data
data = np.array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

#calculate interquartile range 
q3, q1 = np.percentile(data, [75 ,25])
iqr = q3 - q1

#display interquartile range 
iqr

22.5

Question 17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [77]:
group1 =  [0.85, 0.80, 0.82, 0.87, 0.83] 
group2 = [0.78, 0.82, 0.84, 0.80, 0.79]
group3 = [0.90, 0.88, 0.89, 0.86, 0.87]
statistic , p_value = stats.kruskal(group1, group2, group3)
Null = "The median is equal across all groups"
Alternate ="The medina is not equal across all groups"
alpha = 0.05
if(p_value < alpha):
    print(Null)
else:
    print(Alternate)

The median is equal across all groups


Question 18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    Sales: [100, 80, 90, 110, 95]
    Perform a simple linear regression to predict

 sales based on price.


In [58]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
x =  [10, 15, 12, 8, 14];
y =  [100, 80, 90, 110, 95] 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)
# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)

linreg = LinearRegression()
x_train = np.array(x_train).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)
linreg.fit(x_train, y_train)

y_pred = linreg.predict(np.array(x_test).reshape(-1,1))
print("Predicted Array: ")
y_pred

Predicted Array: 


array([[95.38167939]])

Question 19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.


In [21]:
import math
data = [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
x = np.mean(data)
sum = 0;
for i in data:
    sum = sum + (i - x)*(i - x)
n = len(data)
s = math.sqrt(sum / n)
standard_error = s/(math.sqrt(n))
print("standard_error: " , standard_error)

standard_error:  0.2898275349237887


Question 20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
x =  [10, 15, 12, 8, 14];
y =  [25, 30, 28, 20, 26];
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[10, 15, 8, 14]
[12]
[25, 30, 20, 26]
[28]


In [32]:
linreg = LinearRegression()
x_train = np.array(x_train).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)
linreg.fit(x_train, y_train)

LinearRegression()

In [55]:
y_pred = linreg.predict(np.array(x_test).reshape(-1,1))
print("Predicted Array: ")
y_pred

Predicted Array: 


array([[25.53435115]])